# Generated by Django 3.2.6 on 2021-08-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210831_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
