# Generated by Django 3.2.6 on 2021-08-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
    ]
