# Generated by Django 3.2.6 on 2021-08-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210831_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_user',
            field=models.BooleanField(default=False),
        ),
    ]
