# Generated by Django 3.2.6 on 2021-09-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_super_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_super_user',
            new_name='is_superuser',
        ),
    ]
